### PR TITLE
Implement NUT tracking commands

### PR DESCRIPTION
**Pull request by boricj**

### CODE REVIEW

**Comment by jimklimov** [comment]
Sorry, but I do not really see the value of this PR (rather converse - we lose some debuggable/troubleshootable details about failures) nor especially how rearrangement of logging is related to the title "Implement NUT tracking commands" ;-\

**Comment by aquette** [comment]
shared feeling with @jimklimov

**Comment by boricj** [comment]
It is a cleanup that is part of NUT command tracking effort. It just so happens that the original code doesn't need adjustments after implementing command tracking (which was slightly unexpected), so it's limited to cleaning up code and removing HTTP errors 500. I'll add back more logging.

**Comment by jimklimov** [comment]
Ok, thanks for clarification and looking forward to follow-ups :)

**Comment by aquette** [comment]
still, we are losing some log (log_fatal) visibility in the journal.
Note that this could be addressed in the http_die macro

**Pull request merged**
