### PR TITLE
Problem: Data string is incorrectly terminated.

### PR DESCRIPTION
**Pull request by jana-rapava**
Solution: Terminate it correctly.

Signed-off-by: Jana Rapava <janarapava@eaton.com>

### CODE REVIEW

**Comment by boricj** [comment]
Shouldn't `strdup`'ing the original string just work, assuming it is zero-terminated?

**Comment by jana-rapava** [comment]
@boricj from my investigations, it's not zero terminated - it's just some binary blob stored in the DB.

**Comment by boricj** [comment]
I don't see why the original code wouldn't work correctly nor how the fix is functionally different except for adding one more null terminator... Is this really the underlying cause of the data corruption?

Then again, my brain might not be properly working at the end of the day >_<

**Comment by jana-rapava** [comment]
Code from yesterday does not work and is not a good point for comparison.
Original code, which worked but had a memory leak, is here: https://github.com/42ity/fty-rest/commit/01db70aa46272e075ffc642f0a8682744fb9f0e1 .
Refactoring won't get us rid of the problem that we have to turn binary blob into nice and valid std::string - I don't know a way of doing it without null terminators.

**Comment by boricj** [comment]
Cast the pointer to `const char*` and pass the size as the second parameter of the `std::string` constructor: https://en.cppreference.com/w/cpp/string/basic_string/basic_string

**Pull request merged**
