### PR TITLE
Problem: support alert metadata serialization - PQSWMBT-3974

### PR DESCRIPTION
**Pull request by jeffdegott**
* Metadata alert to json (backport from etn-ipm2-rest)

### CODE REVIEW

**Comment by jeffdegott** [comment]
test this please

**Comment by jimklimov** [comment]
The "code duplication" if any, at current stage, concerns two lines :) The gitignore removes three files and adds two (and also removes two fully-generated files, thanks), and there seem to be no related changes for the recipes and sources of those two new. But the PR is green, I guess those files were already in the repo... or not available, not requested, not built, not failed to build - this is also a successful result ;p

Just sanity-checking: are there any more commits awaited?

**Comment by jeffdegott** [comment]
> 
> 
> The "code duplication" if any, at current stage, concerns two lines :)
> 
> The gitignore removes three files and adds two (and th ePR also removes two fully-generated files, thanks), and there seem to be no related changes for the recipes and sources of those two new.
> 
> But the PR is green, I guess either those files were already in the repo... or not available, not requested, not built, not failed to build - this is also a successful result ;p
> 
> Just sanity-checking: are there any more commits awaited?

Jim,
I'm sorry, the modifications on .gitignore concern relicates relating to previous works (cc generated files and related to old/removed ecpp files). I saw them, and corrected them in the process.

**Comment by boricj** [comment]
> The "code duplication" if any, at current stage, concerns two lines :)
I was referring to the whole `src/shared/utils_json.cc` file. It seems it was copy-pasted a long time ago and they haven't been kept rigorously in sync since.

**Comment by jeffdegott** [comment]
> 
> 
> > The "code duplication" if any, at current stage, concerns two lines :)
> 
> I was referring to the whole `src/shared/utils_json.cc` file. It seems it was copy-pasted a long time ago and they haven't been kept rigorously in sync since.

the code duplication concern all the codes related to the SSE processing. For historical/structural/technical reason(s) the fty-rest REST SSE api is potentially crushed by the etn-ipm2-rest SSE api. So fty/etn REST common code must be backported from one side to the other side. :(

**Pull request merged**
