### PR TITLE
Backport changes from master to 1.4

### PR DESCRIPTION
**Pull request by michal42**

### CODE REVIEW

**Comment by michal42** [comment]
release/IPM_Infra-1.4 branch was missing in our libmagic.git, trying again.

**Comment by michal42** [comment]
One of the travis builds failed with
```
Fri Jun  8 13:20:23 UTC 2018: INFO: Building prerequisite 'cxxtools' from Git repository...
fatal: unable to access 'https://github.com/42ity/cxxtools.git/': Failed to connect to github.com port 443: Connection timed out
Command exited with non-zero status 128
```
can we proceed nevertheless?

**Comment by michal42** [comment]
Now Jenkins is timing out after one hour. @jimklimov, can you have a look?

**Comment by aquette** [comment]
Trying the old-school close-reopen method to retrigger jenkins

**Comment by aquette** [comment]
I've just relaunched both failing (timeout on DRAFT build) jenkins jobs from vpn... finger crossed, otherwise force merge!

**Pull request merged**
